# Site settings
title: ' '
email: cuijiaxun_sjtu@163.com
description: ""
baseurl: ""
url: "http://cuijiaxun.github.io"
blogurl: "http://cuijiaxun.github.io/blog"
#twitter_username: karpathy
github_username:  cuijiaxun

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
